apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ikhm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ikhm
    app.kubernetes.io/part-of: tkrw-pr712-0075-0022-app
  name: devfile-sample-ikhm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ikhm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ikhm
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0022-tenant/tkrw-pr712-0075-0022-app/devfile-sample-ikhm@sha256:43fe0b67c821dd8aac57604ef2ed97e8160e59d03d0a13fa9c300e19a2178873
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
